# generated by mBlock5 for Arduino Alvik
# by Scuola di Robotica (scuoladirobotica.it)
# codes make you happy

import sys
from arduino_alvik import ArduinoAlvik
from time import sleep_ms
import time

# Event handlers
def when_cancel_pressed():
    global robot, stop_line_follower, KeepLooping

    robot.left_led.set_color(0, 0, 0)
    robot.left_led.set_color(0, 0, 0)
    KeepLooping = 0
    robot.stop()

# Initialization
robot = ArduinoAlvik()

# setup button cancel press events
robot.__on_touch_cancel_callbacks = []
def on_touch_cancel_call():
    global robot
    for callback in robot.__on_touch_cancel_callbacks:
        callback()
robot.on_touch_cancel_pressed(on_touch_cancel_call)
robot.__on_touch_cancel_callbacks.append(when_cancel_pressed)
robot.begin()

# initialize variables
KeepLooping = 0

# Program
def main():
    global robot, stop_line_follower, KeepLooping

    KeepLooping = 1
    while KeepLooping == 1:
      robot.right_led.set_color(1,0,0)
      robot.left_led.set_color(0,1,0)
      time.sleep(1)
      robot.left_led.set_color(1,0,0)
      robot.right_led.set_color(0,1,0)
      time.sleep(1)

main()
